server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/courier_service?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        use-new-id-generator-mappings: true
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ""
    password: ""
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
